anthill/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from olivet import settings

from . import views

app_name = 'anthill'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.signin, name='login'),
    path('register/', views.register, name='register'),
    path('accounts/login/', views.signin, name="login"),
    path('cabinet/', views.cabinet, name='cabinet'),
    path('partner/', views.partner, name='partner'),

    path('subscribe/', views.subscribe, name='subscribe'),
    path('citymap/', views.citymap, name='citymap'),
    path('places/', views.places, name='places'),
    path('contact/', views.contact, name='contact'),
    path('place/', views.place, name='place'),
    path('city_location/', views.city_location, name='city_location'),
    path('booking/', views.booking, name='booking'),

    path('not_implemented/', views.not_implemented, name='not_implemented/'),
    path('like/', views.like, name='like'),
    path('like_comment/', views.like_comment, name='like_comment'),
    path('thanks/', views.comment_thanks, name='comment_thanks'),

    #api
    path('place_import/', views.place_import, name='place_import'),

    url(r'^tinymce/', include('tinymce.urls'))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olivet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from anthill import views

urlpatterns = [
    path('', include('anthill.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path("", views.index, name="home"),
    path('olivet/', admin.site.urls),
]

anthill/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.gis.db import models as geomodels
from imagekit.models import ImageSpecField
from tinymce.models import HTMLField
from imagekit.processors import ResizeToFill


class Subscriber(models.Model):
    email = models.EmailField(blank=False, unique=True)
    time = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.email


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    text = models.TextField()

    def __str__(self):
        return self.subject


class City(models.Model):
    name = models.CharField(max_length=150, blank=False, unique=True)
    description = models.TextField(null=True)
    geometry = geomodels.PointField()
    main_image = models.ImageField(upload_to="city_img", null=True)
    city_photo = ImageSpecField(source='main_image',
                                processors=[ResizeToFill(370, 420)],
                                format='JPEG',
                                options={'quality': 60})

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'cities'

    def __str__(self):
        return self.name


class Place(models.Model):
    ACTIVE = 'AC'
    ECO = 'EC'
    NATURE = 'NT'
    ARCHITECTURE = 'AR'
    OTHER = 'OT'

    TYPE_OF_PLACE_CHOICE = (
        (ACTIVE, 'Активний відпочинок'),
        (ECO, 'Екотуризм'),
        (NATURE, 'Природа та парки'),
        (ARCHITECTURE, 'Музеї, архітектура, культура'),
        (OTHER, 'Інше')
    )

    name = models.CharField(max_length=150, blank=False)
    geometry = geomodels.PointField(null=True)
    type = models.CharField(max_length=2, choices=TYPE_OF_PLACE_CHOICE, default=NATURE)

    approved = models.BooleanField(default=False)

    header_img = models.ImageField(upload_to="place/headers", null=True)

    place_header = ImageSpecField(source='header_img',
                                processors=[ResizeToFill(1920, 803)],
                                format='JPEG',
                                options={'quality': 80})

    place_logo = ImageSpecField(source='header_img',
                                processors=[ResizeToFill(290, 240)],
                                format='JPEG',
                                options={'quality': 80})

    address = models.CharField(max_length=255, null=True)
    content = HTMLField()

    price = models.IntegerField(default=-1)
    phone = models.CharField(max_length=255)
    site = models.URLField(null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    email = models.EmailField(blank=True, null=True)

    city = models.ForeignKey(City, on_delete=models.CASCADE)

    # Features
    free = models.BooleanField(default=False)
    for_kids = models.BooleanField(default=False)
    inclusive = models.BooleanField(default=False)
    extreme = models.BooleanField(default=False)
    romantic = models.BooleanField(default=False)
    family = models.BooleanField(default=False)


    visit_count = models.IntegerField(default=0)
    user_likes = models.ManyToManyField(User)
    rating = models.IntegerField(default=-1)
    total_ratings = models.IntegerField(default=-1)
    google_id = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'places'
        unique_together = [['name', 'geometry']]

    def natural_key(self):
        return (self.name, self.geometry.x, self.geometry.y)


class Comment(models.Model):
    subject = models.CharField(max_length=100, blank=False)
    text = models.TextField()
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True, blank=True)
    rating = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.subject


class Image(models.Model):
    title = models.CharField(max_length=250)
    data = models.ImageField(upload_to="coworkings/albums")
    data_thumbnail = ImageSpecField(source='data',
                                    processors=[ResizeToFill(250, 180)],
                                    format='JPEG',
                                    options={'quality': 60})
    date_uploaded = models.DateTimeField(auto_now_add=True)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

anthill/forms.py
from django import forms
from django.forms import ModelForm
from anthill.models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'text', 'rating']

anthill/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import D
from django.core import serializers
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.db.models import Count

import logging

# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.contrib.admin.views.decorators import staff_member_required

from anthill.models import City, Subscriber, Place, Feedback, Comment, Image
from anthill.forms import CommentForm

logger = logging.getLogger(__name__)


# START Infra pages


def index(request):
    logger.debug('index() - page requested')
    return render(request, 'anthill/index.html', get_statistics())


def contact(request):
    logger.debug('contact() - page requested')
    if request.POST:
        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        comment = request.POST.get("comment")
        logger.info("contact() - saving %s, %s from %s", name, email, subject)
        feedback = Feedback(name=name, email=email, subject=subject, text=comment)
        Feedback.save(feedback)
        return render(request, 'anthill/contact.html', {"message": "Дякуємо за відгук!"})
    else:
        return render(request, 'anthill/contact.html')


def subscribe(request):
    logger.debug('subscribe() - page requested')
    if request.method == 'POST':
        mail = request.POST['email-sub']
        s = Subscriber(email=mail)
        try:
            s.save()
        except Exception as exc:
            logger.warning("subscribe() - can't save: %s", exc)

    return render(request, 'anthill/subscribe.html')


@csrf_exempt
@login_required
def like(request):
    try:
        place_id = request.POST.get('place_id')

        place = Place.objects.get(pk=place_id)
        place.user_likes.add(request.user)
        return HttpResponse(200)

    except Exception as exc:
        logger.error('like() - error: ', exc)
        return HttpResponse(500)


@csrf_exempt
def like_comment(request):
    comment_id = request.POST.get('comment_id')
    comment = Comment.objects.get(pk=comment_id)
    comment.likes += 1
    comment.save()
    return HttpResponse(200)


def signin(request):
    logger.debug('signin() - page requested')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        next_page = request.POST.get('next')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            logger.info("signin() - user: %s", username)
            login(request, user)

            if request.POST.get('rememb-check'):
                request.session.set_expiry(0)

            if next_page != "None":
                return redirect(next_page)

            return redirect('/')
        else:
            context = {'error_message': 'Помилка при вході! Перевірте дані'}
            return render(request, 'anthill/login.html', context)
    else:
        context = {"next": request.GET.get('next')}
        return render(request, 'anthill/login.html', context)


def register(request):
    logger.debug('register() - page requested')
    if request.method == 'POST':
        email = request.POST.get('email')
        fname = request.POST.get('firstname')
        lname = request.POST.get('lastname')

        password = request.POST.get('password')
        new_user = get_user_model().objects.create_user(username=email,
                                                        password=password,
                                                        email=email)
        new_user.is_active = True
        new_user.first_name = fname
        new_user.last_name = lname
        new_user.save()

        request.session['user_name'] = email
        request.session['user_password'] = password
        request.session['user_email'] = email

        logger.info("register() - user created: %s, %s", email, fname)
        return redirect('/')

    else:
        return render(request, 'anthill/register.html', {})


@login_required
def cabinet(request):
    return render(request, 'anthill/cabinet.html', {})

@login_required
def partner(request):
    return render(request, 'anthill/partner_cabinet.html', {})

@login_required
def booking(request):
    return render(request, 'anthill/booking.html', {})


def logout_view(request):
    logger.debug('logout() - page requested')
    logout(request)
    return redirect('/')

# EVENTS pages


def not_implemented(request):
    return render(request, 'anthill/notimplemented.html')

# END Infra pages


# START places pages
@require_http_methods(["GET"])
def citymap(request):
    logger.debug('citymap() - page requested')
    city_val = request.GET.get("city")
    type_val = request.GET.get("category")

    all_cities = City.objects.all()
    return render(request, 'anthill/citymap.html', {"cities": all_cities, "city_val": city_val, "category": type_val })


def city_location(request):
    city_id = request.GET.get("id")
    city = City.objects.get(pk=city_id)

    context = {
        'city': city.name.encode("utf-8").decode("utf-8"),
        'x': city.geometry.x,
        'y': city.geometry.y
    }

    return JsonResponse(context)


@require_http_methods(["GET"])
def places(request):
    """
    Returns list of objects according to filters
    :param request:
    :return:
    """
    logger.debug('places() - page requested')
    context = filter_places(request)
    return render(request, 'anthill/places.html', context)


def place(request):
    if request.method == 'POST':
        save_comment(request)
        return HttpResponseRedirect("/thanks", {})
    else:
        place_id = request.GET.get("id")

    context = {}
    place = Place.objects.get(pk=place_id)
    context['place'] = place
    place.visit_count += 1
    place.save()

    if Image.objects.filter(place__id=place_id).count() > 0:
        images = Image.objects.filter(place__id=place_id)
        context['images'] = images

    if Place.objects.filter(user_likes__id = request.user.id).count() > 0:
        print('liked')
        context['liked'] = True

    context['comments'] = Comment.objects.filter(place__id=place_id)

    return render(request, 'anthill/place.html', context)


def comment_thanks(request):
    return render(request, 'anthill/comment_thanks.html', {})


# place scrapper api
@staff_member_required
def place_import(request):
    if request.method == "POST":
        json_text = request.FILES['file'].read().decode("utf-8")
        json_data = json.loads(json_text)
        logger.info('place_import() - importing %s', json_data)
        try:
            save_json_places(json_data)
            return redirect('/')
        except Exception as e:
            logger.error('place_import() - error: %s', e)
            return HttpResponse(500)

    if request.method == "GET":
        return render(request, 'anthill/place_import.html')



def save_comment(request):
    form = CommentForm(request.POST)
    place_id = request.POST.get('place_id')
    if form.is_valid():
        comment = form.save(commit=False)

        place = Place.objects.get(pk=place_id)

        comment.author = request.user
        comment.place = place
        comment.save()

    else:
        logging.error('saving wrong form ' + form.errors)
    return place_id


# END places pages
def filter_places(request):
    """
    Filtering places by user input
    :param request:
    :return:
    """
    city = request.GET.get("city")
    category = request.GET.get("category")
    query = {}

    if category != "all":
        query["type"] = category

    all_places = set_full_filter(city, query, request)

    places_json = serializers.serialize('json', all_places, fields=["geometry", "name", "id"])
    context = {"places": all_places, "places_json": places_json}

    return context


def set_full_filter(city, query, request):
    filter_values = ['free', 'for_kids', 'inclusive', 'extreme', 'family', 'romantic']

    for val in filter_values:
        if request.GET.get(val) == "true":
            query[val] = True

    query['approved'] = True

    if city == "closest":
        lat = float(request.GET.get("lat"))
        lon = float(request.GET.get("lon"))
        location_point = Point(lon, lat)
        current_city = City.objects.filter(geometry__distance_lte=(location_point, D(km=10)))
        if current_city:
            current_city = current_city[0]
            query['city__id'] = current_city.id

        all_places = Place.objects.filter(**query).annotate(number_of_feebacks=Count('comment'))

    else:
        query['city__id'] = city
        all_places = Place.objects.filter(**query).annotate(number_of_feebacks=Count('comment'))

    return all_places


def get_statistics():
    statistics = {
        'cities': City.objects.all().annotate(number_of_places=Count('place')),
        'locations_count': Place.objects.count(),
        'comments_count': Comment.objects.count(),
        'users_count': User.objects.count(),
        'places': Place.objects.filter(approved=True).annotate(number_of_feebacks=Count('comment'))[:10]
    }

    return statistics


def save_json_places(json_data):
    for place_json in json_data:

        place = Place()
        place.name = place_json['name']
        place.address = place_json['address']
        place.rating = place_json['rating']
        place.total_ratings = place_json['total_ratings']
        place.google_id = place_json['google_id']
        place.geometry = Point(place_json['lan'], place_json['lat'])
        place.type = place_json['types']

anthill/templates/anthill/basewhitefooter.html
{% extends 'anthill/basesign.html' %}
{% load static %}


{% block content %}

{% block page %}

{% endblock %}

		<!-- footer block module
			================================================== -->
		<footer class="footer footer-black">
			<div class="container">

				<div class="footer__up-part">
					<div class="row">
						<div class="col-md-4">

							<div class="footer__widget text-widget">
								<img src="{% static 'anthill/images/logo_sm.png' %}" alt="spacetime-logo">
								<p class="footer__widget-description">
									База локацій для будь-якої події.
								</p>
							</div>

						</div>
						<div class="col-md-4">

							<div class="footer__widget subscribe-widget">
								<h2 class="footer__widget-title footer__widget-title-white">
									Підписка
								</h2>
								<p class="footer__widget-description">
									Отримуй листи про наші оновлення
								</p>
								<form class="footer__subscribe-form" method="post" action="subscribe/">
									{% csrf_token %}
									<input class="footer__subscribe-input" type="text" name="email-sub" id="email-sub" placeholder="Твій email" />
									<button class="footer__subscribe-button footer__subscribe-button-primary" type="submit">
										<i class="la la-arrow-circle-o-right" aria-hidden="true"></i>
									</button>
								</form>
							</div>

						</div>
						<div class="col-md-4">

							<div class="footer__widget text-widget">
								<h2 class="footer__widget-title footer__widget-title-white">
									Контактна інформація
								</h2>
								<p class="footer__widget-description">
									Вінниця <br>
									gunkooleksii@gmail.com<br>
								</p>
							</div>

						</div>
					</div>
				</div>

				<div class="footer__down-part footer__down-part-black">
					<div class="row">
						<div class="col-md-7">
							<p class="footer__copyright">
								© SpaceTime 2019 - Всі права захищено
							</p>
						</div>
						<div class="col-md-5">
							<ul class="footer__social-list">
								<li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

			</div>

		</footer>
{% endblock %}

anthill/templates/anthill/comment_thanks.html
{% extends 'anthill/basesign.html' %}
{% load static %}

{% block title %}
	<title>Підписка - SpaceTime</title>
{% endblock%}


{% block content %}
<!-- contact-page-block
			================================================== -->
		<section class="contact-page">
			<div class="container">
				<span class="contact-page__short-title">
					Ваша відгук збережено
				</span>
				<h1 class="contact-page__title">
					Дякуємо за те що ділитесь з нами!
				</h1>

				<a onclick="window.history.back();" class="add-list-btn btn-main">Повернутись</a>
			</div>
		</section>
		<!-- End contact-page-block -->
{% endblock %}

anthill/templates/anthill/index.html
{% extends 'anthill/base.html' %}
{% load static %}

{% block title %}
	<title>SpaceTime - незабутній відпочинок поруч</title>
{% endblock%}

{% block content %}
<!-- discover-module section
			================================================== -->
		<section class="discover">
			<div class="container">
				<p class="discover__description">Обирай цікаві місця та організовуй подорожі Україною з нами</p>

				<h1 class="discover__title places-tab">
					Незабутній відпочинок поруч!
				</h1>


				<ul class="discover__list">
					<li class="discover__list-item">
						<a class="place active-list" href="#"><i class="la la-compass" aria-hidden="true"></i>Локації</a>
					</li>
				</ul>

				<form class="discover__form">

					<select class="discover__form-input js-example-basic-multiple" id="sltCities" name="sltCities">
						<option value="closest">Обери місто</option>
						{% for city in cities %}
							<option value="{{ city.id }}">{{ city.name }}</option>
						{% endfor %}
					</select>
					<select class="discover__form-input js-example-basic-multiple" id="sltType" name="sltType">
						<option value="all">Усі види</option>
						<option value="AC">Активний відпочинок</option>
						<option value="EC">Екотуризм</option>
						<option value="NT">Природа та парки</option>
						<option value="AR">Музеї, архітектура, культура</option>
					</select>

					<button class="btn-default btn-default-red" type="submit" id="btnSearch" name="btnSearch"><i class="fa fa-search" aria-hidden="true"></i> Пошук</button>
				</form>

			</div>
		</section>
		<!-- End discover-module section -->

		<!-- services-block
			================================================== -->
		<section class="services services-trans" id="services">
			<div class="container">


				<div class="services__box services__box-half-negative">
					<div class="row">

						<div class="col-xl-4 col-md-4 col-sm-6">

							<!-- services-post2 module -->
							<a href="#" class="services-post2">
								<div class="services-post2__content">
									<i class="la la-map" aria-hidden="true"></i>
									<h2 class="services-post2__title">
										Зручний пошук
									</h2>
								</div>
							</a>
							<!-- end services-post2 module -->

						</div>

						<div class="col-xl-4 col-md-4 col-sm-6">

							<!-- services-post2 module -->
							<a href="#" class="services-post2">
								<div class="services-post2__content">
									<i class="la la-street-view" aria-hidden="true"></i>
									<h2 class="services-post2__title">
										Найближчі локації
									</h2>
								</div>
							</a>
							<!-- end services-post2 module -->

						</div>

						<div class="col-xl-4 col-md-4 col-sm-6">

							<!-- services-post2 module -->
							<a href="#" class="services-post2">
								<div class="services-post2__content">
									<i class="la la-rocket" aria-hidden="true"></i>
									<h2 class="services-post2__title">
										Персоналізований контент
									</h2>
								</div>
							</a>
							<!-- end services-post2 module -->
						</div>

					</div>
				</div>

			</div>
		</section>
		<!-- End services-block -->

<!-- trending-places-block
			================================================== -->
		<section class="trending-places">
			<div class="container">

				<!-- section-header module -->
				<div class="section-header">
					<h1 class="section-header__title">
						Останні додані локації
					</h1>
					<p class="section-header__description">
						На сьогодні зареєстровано {{ locations_count }} локацій
					</p>
				</div>
				<!-- end section-header module -->


				<div class="trending-places__box owl-wrapper">
					<div class="owl-carousel" data-num="5">
						{% for place in places %}
						<div class="item">
														<!-- place-post module -->
														<div class="place-post">
															<div class="place-post__gal-box">
																<img class="place-post__image" src="{{ place.place_logo.url }}" alt="place-image">
																<a class="place-post__like" href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
															</div>
															<div class="place-post__content">
																<h2 class="place-post__title">
																	<a href="/place/?id={{ place.id }}">{{ place.name }}</a>
																</h2>
																<p class="place-post__description">
																	{{ place.get_type_display }}
																	<span class="place-post__description-review">
																		<i class="fa fa-comment-o" aria-hidden="true"></i>
																		{{ place.number_of_feebacks }} відгуків
																	</span>
																</p>
																<p class="place-post__address">
																	<i class="fa fa-map-marker" aria-hidden="true"></i>
																	{{ place.city }}
																</p>
															</div>
														</div>
							</div>
							{% endfor %}

					</div>
				</div>
				<div class="center-button">
					<a class="text-btn" href="/citymap">
						Відкрити всі
					</a>
				</div>
			</div>
		</section>
		<!-- End trending-places-block -->

		<!-- banner-block
			================================================== -->
		<section class="banner" id="subscribe">
			<div class="container">
				<div class="row">
					<div class="col-md-8">

						<!-- section-header module -->
						<div class="section-header">
							<h1 class="section-header__title white-style">
								Приєднатись до спільноти!
							</h1>
							<p class="section-header__description white-style">
								Долучайтесь та діліться своїми улюбленними місцями
							</p>
						</div>
						<!-- end section-header module -->

					</div>
					<div class="col-md-4">
						<a class="btn-default" href="{% url 'anthill:login' %}">
							<i class="fa fa-check-circle-o" aria-hidden="true"></i>
							Приєднатись!
						</a>
					</div>
				</div>
			</div>
		</section>
		<!-- End banner-block -->

<!-- top-experience-block
			================================================== -->
		<section class="top-experience top-experience-rated">
			<div class="container">

				<!-- section-header module -->
				<div class="section-header">
					<h1 class="section-header__title">
						Міста
					</h1>
					<p class="section-header__description">
						Наша мета - зібрати усі цікаві місця України та допомогти вам організувати свій відпочинок
					</p>
				</div>
				<!-- end section-header module -->


				<div class="top-experience__box owl-wrapper">
					<div class="owl-carousel" data-num="3">
						{% for city in cities %}
						<div class="item">
							<!-- place-gal module -->
							<div class="place-gal">
								<img class="place-gal__image" src="{{ city.city_photo.url }}" alt="place-image">
								<div class="place-gal__content">
									<h2 class="place-gal__title">
										<a href="#">
											<img src="upload/flag1.jpg" alt="">
											{{ city.name }}
										</a>
									</h2>
									<ul class="place-gal__list">
										<li class="place-gal__list-item">
											<a href="#">{{ city.number_of_places }} локацій на сайті</a>
										</li>
									</ul>
									<a class="btn-default" href="/citymap/?city={{ city.id }}&category=all">
										<i class="fa fa-caret-right" aria-hidden="true"></i>
										Відкрити
									</a>
								</div>
							</div>
							<!-- end place-gal module -->
						{% endfor %}
						</div>
					</div>
				</div>

			</div>
		</section>
		<!-- End top-experience-block -->


		<!-- how-it-work-block
			================================================== -->
		<section class="how-it-work how-it-work-mapbg" id="process">
			<div class="container">

				<!-- section-header module -->
				<div class="section-header">
					<h1 class="section-header__title">
						Досліджуй країну разом з нами
					</h1>
					<p class="section-header__description">
						Ми готові допомогти тобі на всіх етапах
					</p>
				</div>
				<!-- end section-header module -->

				<div class="how-it-work__box">
					<div class="row">

						<div class="col-lg-4 col-md-6">

							<!-- how-work-post module -->
							<div class="how-work-post">

								<span class="how-work-post__icon">
									<i class="la la-compass" aria-hidden="true"></i>
								</span>

								<h2 class="how-work-post__title">
									Досліджуй місто
								</h2>

								<p class="how-work-post__description">
									Обери місто яке ти маєш відвідати та переглянь карту локацій
								</p>

							</div>
							<!-- end how-work-post module -->

						</div>

						<div class="col-lg-4 col-md-6">

							<!-- how-work-post module -->
							<div class="how-work-post">

								<span class="how-work-post__icon">
									<i class="la la-binoculars" aria-hidden="true"></i>
								</span>

								<h2 class="how-work-post__title">
									Шукай цікаві міця
								</h2>

								<p class="how-work-post__description">
									Ми підберем саме ті локацій які дадуть тобі найбільше емоцій
								</p>

							</div>
							<!-- end how-work-post module -->

						</div>



						<div class="col-lg-4 col-md-6">

							<!-- how-work-post module -->
							<div class="how-work-post">

								<span class="how-work-post__icon">
									<i class="la la-plus-circle" aria-hidden="true"></i>
								</span>

								<h2 class="how-work-post__title">
									Додавай до списку
								</h2>

								<p class="how-work-post__description">
									Зберігай цікаві локації та складай оптимальний маршрут щоб встигнути побачити усе
								</p>

							</div>
							<!-- end how-work-post module -->

						</div>

					</div>
				</div>

			</div>
		</section>
		<!-- End how-it-work-block -->
{% endblock %}

anthill/templates/anthill/notimplemented.html
{% extends 'anthill/basesign.html' %}
{% load static %}


{% block content %}
<!-- contact-page-block
			================================================== -->
		<section class="contact-page">
			<div class="container">
				<span class="contact-page__short-title">
					Доведеться трошки зачекати
				</span>
				<h1 class="contact-page__title">
					Цей розділ ще в розробці...
				</h1>
				<p class="contact-page__description">
					Якщо ви хочете бути одним з перших - звяжіться з нами
                    <a href="/contact">Зв'язатись</a>
				</p>

			</div>
		</section>
		<!-- End contact-page-block -->
{% endblock %}

anthill/templates/anthill/places.html
<div class="row vacancy" id="vacancy">
{% for place in places %}
<div class="col-md-6">
							<!-- place-post module -->
							<div class="place-post">
								<div class="place-post__gal-box">
									<img class="place-post__image" src="{{ place.place_logo.url }}" alt="place-image">
									<a class="place-post__like" href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
								</div>
								<div class="place-post__content">
									<h2 class="place-post__title">
										<a href="/place/?id={{ place.id }}">{{ place.name }}</a>
									</h2>
									<p class="place-post__description">
										{{ place.get_type_display }}
										<span class="place-post__description-review">
											<i class="fa fa-comment-o" aria-hidden="true"></i>
											{{ place.number_of_feebacks }} відгуків
										</span>
									</p>
									<p class="place-post__address">
										<i class="fa fa-map-marker" aria-hidden="true"></i>
										{{ place.address }}
									</p>
								</div>
							</div>
							<!-- end place-post module -->
						</div>
{% endfor %}

<script>
	{% if places_json %}
		var places_js = JSON.parse('{{ places_json|safe }}');
		addMarker(places_js);
	{% endif %}
</script>
</div>